{% set name = "django-streamfield" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-streamfield-{{ version }}.tar.gz
  sha256: 975efef4a87fb6c0c81add65d1141337c87ef3e823ee3f9dc4213afff740fd74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=4.2

test:
  imports:
    - streamfield
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/raagin/django-streamfield
  summary: StreamField for native Django Admin or with Grappelli
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
